name: roamin
favicon: null
layout_spectrum: 0.93294
typography_spectrum: 0.41911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a2a2a2'
    - '#2f2e2c'
    - '#e5e4e0'
    - '#676767'
  brandStrength: 0.75
  lightness: 0.754504
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
