name: roamin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87154
title: current test site / possible future landing or navigation site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced0cd'
    - '#0e0c0d'
    - '#9c9c9a'
    - '#333333'
    - '#238b02'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
