name: roamin
favicon: null
layout_spectrum: 0.23367
typography_spectrum: 0.68065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a2a2a2'
    - '#2f2e2c'
    - '#e5e4e0'
    - '#676767'
  brandStrength: 0.690315
  lightness: 0.754504
  saturation: 0.203828
  rhythmicContrast: 1
purpose: []
