analytics: {}
color:
  brandColors:
    - '#000000'
    - '#a2a2a2'
    - '#2f2e2c'
    - '#e5e4e0'
    - '#676767'
  brandStrength: 0.690315
  lightness: 0.754504
  rhythmicContrast: 1
  saturation: 0.203828
cta: {}
layout_spectrum: 0.612612
name: roamin
opengraph: {}
purpose: []
typography_spectrum: 0.268018
