analytics: {}
color:
  brandColors:
    - '#000000'
    - '#a2a2a2'
    - '#2f2e2c'
    - '#e5e4e0'
    - '#676767'
  brandStrength: 0.8125
  lightness: 0.25
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 0.033783
name: roamin
opengraph: {}
purpose: []
typography_spectrum: 0.6572682
