name: roamin
favicon: null
layout_spectrum: 0.23055
typography_spectrum: 0.2698
title: current test site / possible future landing or navigation site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefcff'
    - '#a60c02'
    - '#969195'
    - '#dd5954'
    - '#e88f92'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
