name: roamin
favicon: null
layout_spectrum: 0.61848
typography_spectrum: 0.28437
title: current test site. future about page?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefcff'
    - '#a60c02'
    - '#969195'
    - '#dd5954'
    - '#e88f92'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
