name: roamin
favicon: null
layout_spectrum: 0.59307
typography_spectrum: 0.82921
title: current test site / possible future landing or navigation site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a2a2a2'
    - '#2f2e2c'
    - '#e5e4e0'
    - '#676767'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
