typography_spectrum: 0.94629
content_rating:
  adult: false
color:
  brandColors:
    - '#dbd9dc'
    - '#4a474e'
    - '#606374'
    - '#9e9b96'
    - '#c5b7b7'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.19984
analytics:
  google: null
  facebook: null
  twitter: null
name: roamin
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Elsewhere
    url: 'https://portfolio.roamin.ca'
    type: external
  - name: Twitter
    url: 'https://www.twitter.com/roamin'
    type: external
  - name: Medium
    url: 'https://medium.com/@roamin'
    type: external
  - name: Last FM
    url: 'https://www.last.fm/user/roamin'
    type: external
  - name: Mixcloud
    url: 'https://www.mixcloud.com/roamin/'
    type: external
  - name: Cymbal FM
    url: 'https://www.cymbal.fm/roamin'
    type: external
  - name: /Favourites
    url: 'https://slashfavorites.com/#roamin'
    type: external
  - name: Listen L8er
    url: 'https://8tracks.com/users/roamin/collections'
    type: external
favicon: null
title: future nav/about page
description: who knows?
purpose: []
