name: roamin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87154
title: current test site / possible future landing or navigation site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d60000'
    - '#ffffff'
    - '#e4bb99'
    - '#897162'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
